version: '3.4'

services:
  base:
    image: com.io/k8.demo.base:v1
    build:
      context: .
      dockerfile: Dockerfile.base

  frontend:
    image: com.io/k8.demo.frontend:v1
    build:
      context: .
      dockerfile: src/K8.FrontEnd/Dockerfile
      args:
        PAT: ${PAT}
        FEED: ${FEED}
    environment:
      - MSI_ENDPOINT=${MSI_ENDPOINT}
      - MSI_SECRET=${MSI_SECRET}
    ports:
      - "5000:5000"

  cronjobs:
    image: com.io/k8.demo.cronjobs:v1
    build:
      context: .
      dockerfile: src/K8.LongProcess/Dockerfile
      args:
        PAT: ${PAT}
        FEED: ${FEED}
    environment:
      - MSI_ENDPOINT=${MSI_ENDPOINT}
      - MSI_SECRET=${MSI_SECRET}
