apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
      kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: k8-frontend-app.local
    http:
      paths:
      - backend:
          serviceName: k8-frontend-service
          servicePort: 5000



# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: k8demo-ingress
#   annotations:
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /
#           backend:
#             serviceName: k8-frontend-service
#             servicePort: 5000
