# https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-job
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import-job
            image: k8.demo.cronjobs:v1
            command: ["./K8.LongProcess"]
            args:
            - "-t Import"
          restartPolicy: OnFailure
