# Default values for k8netcorev2.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: com.io
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

global:
  msi:
    endpoint: http://host.docker.internal:5050/oauth2/token
    secret: 19603b25-f198-4156-a82a-b68d40681455
